version: '2'
services:
    jhipster2-app:
        image: jhipster2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster2-mysql:3306/jhipster2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipster2-elasticsearch:9300
        ports:
            - 8080:8080
    jhipster2-mysql:
        extends:
            file: mysql.yml
            service: jhipster2-mysql
    jhipster2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster2-elasticsearch
